/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

package io.spine.code.proto;

import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.FileDescriptorSet;
import com.google.protobuf.Descriptors.FileDescriptor;
import io.spine.io.Resource;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.Set;
import java.util.function.Predicate;

import static com.google.common.base.Preconditions.checkNotNull;
import static io.spine.io.IoPreconditions.checkExists;
import static io.spine.util.Exceptions.newIllegalStateException;
import static io.spine.util.Predicates2.distinctBy;
import static java.util.stream.Collectors.toList;
import static java.util.stream.Collectors.toSet;

/**
 * A utility class for obtaining Protobuf file descriptors.
 */
public final class FileDescriptors {

    /**
     * Extension of the descriptor set files.
     */
    public static final String DESC_EXTENSION = ".desc";

    /**
     * The name of the descriptor set file.
     *
     * <p>The file contains a {@link FileDescriptorSet} describing the Protobuf of a given module.
     *
     * <p>The file is generated by the Protobuf compiler in the build process.
     */
    public static final String KNOWN_TYPES = "known_types" + DESC_EXTENSION;

    /** Prevents instantiation of this utility class. */
    private FileDescriptors() {
    }

    /**
     * Returns descriptors of all {@code .proto} files described in the descriptor set file.
     *
     * @param descriptorSetFile
     *         the path to the file generated by the Protobuf compiler that
     *         contains descriptors of the project {@code .proto} files
     * @return a list of descriptors
     */
    public static List<FileDescriptorProto> parse(File descriptorSetFile) {
        return parseAndFilter(descriptorSetFile, descriptor -> true);
    }

    /**
     * Returns descriptors of `.proto` files described in the descriptor set file
     * that match the filter predicate.
     *
     * @param descriptorSet
     *         the file generated by the Protobuf compiler that
     *         contains descriptors of the project {@code .proto} files
     * @param filter
     *         a filter predicate to apply to the files
     * @return a list of descriptors
     */
    private static List<FileDescriptorProto>
    parseAndFilter(File descriptorSet, Predicate<FileDescriptorProto> filter) {
        checkExists(descriptorSet);
        List<FileDescriptorProto> files;
        try (var fis = new FileInputStream(descriptorSet)) {
            var fileSet = FileDescriptorSetReader.parse(fis);
            files = fileSet.getFileList().stream()
                    .filter(filter)
                    .collect(toList());
        } catch (IOException e) {
            throw newIllegalStateException(
                    e, "Cannot get proto file descriptors. Path: `%s`.", descriptorSet
            );
        }
        return files;
    }

    /**
     * Loads the descriptor files from the classpath.
     *
     * @return the set of {@linkplain FileDescriptorProto file descriptors}
     *         contained in the loaded files
     */
    static Set<FileDescriptorProto> load() {
        var resources = DescriptorSetReferenceFile.loadAll();
        var files = resources.stream()
                .map(FileDescriptors::loadFrom)
                .flatMap(set -> set.getFileList().stream())
                .filter(distinctBy(FileDescriptorProto::getName))
                .collect(toSet());
        return files;
    }

    /**
     * Reads an instance of {@link FileDescriptorSet} from the given {@link URL}.
     */
    private static FileDescriptorSet loadFrom(Resource resource) {
        checkNotNull(resource);
        return resource.exists()
               ? doLoadFrom(resource)
               : FileDescriptorSet.getDefaultInstance();
    }

    private static FileDescriptorSet doLoadFrom(Resource resource) {
        try (var stream = resource.open()) {
            var parsed = FileDescriptorSetReader.parse(stream);
            return parsed;
        } catch (IOException e) {
            throw newIllegalStateException(
                    e,
                    "Unable to load file descriptor set from `%s`.",
                    resource
            );
        }
    }

    /**
     * Tells if two descriptors represent the same file.
     */
    public static boolean sameFiles(FileDescriptor f1, FileDescriptor f2) {
        var sameName = f2.getFullName()
                         .equals(f1.getFullName());
        var samePackage = f2.getPackage()
                            .equals(f1.getPackage());
        return sameName && samePackage;
    }

    /**
     * Verifies if the passed file declares types under the "google" package.
     */
    public static boolean isGoogle(FileDescriptor file) {
        var packageName = PackageName.of(file.getPackage());
        return packageName.isGoogle();
    }
}
