/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.given.type;

import "spine/options.proto";
import "google/protobuf/wrappers.proto";

option (type_url_prefix) = "type.spine.io";
option java_package="io.spine.given.type";
option java_multiple_files = true;

// Marks all types in this file as `beta_type`.
option (beta_all) = true;

message ImplicitBetaType {
    string value = 1;
}

service ImplicitBetaService {
    rpc Get(google.protobuf.StringValue) returns (google.protobuf.StringValue);
}

enum ImplicitBetaEnum {
    BIE_RESERVED = 0;
    BIE_ONE = 1;
    BIE_TWO = 2;
}

message ExplicitNonBetaType {
    option (beta_type) = false;
}
