/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

package spine.given.type;

import "spine/options.proto";
import "google/protobuf/wrappers.proto";

option (type_url_prefix) = "type.spine.io";
option java_package="io.spine.given.type";
option java_multiple_files = true;

// See https://protobuf.dev/reference/java/java-generated/#service
option java_generic_services = true;

message ExplicitBetaType {
    option (beta_type) = true;
}

message ExplicitInternalType {
    option (internal_type) = true;
}

message ExplicitSpiType {
    option (SPI_type) = true;
}

service ExplicitSpiService {
    option (SPI_service) = true;
    rpc Get(google.protobuf.StringValue) returns (google.protobuf.StringValue);
}

message ExplicitExperimentalType {
    option (experimental_type) = true;
}
