/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.given.type;

import "spine/options.proto";
import "google/protobuf/wrappers.proto";

option (type_url_prefix) = "type.spine.io";
option java_package="io.spine.given.type";
option java_multiple_files = true;

// A bunch of fields with different API level options and without options.
message Filderation {
    string beta_field = 1 [(beta) = true];
    string non_beta = 2;
    string explicit_non_beta = 3 [(beta) = false];

    int32 experimental_field = 4 [(experimental) = true];
    int32 non_experimental = 5;
    int32 explicit_non_experimental = 6 [(experimental) = false];

    bool internal_field = 7 [(internal) = true];
    bool non_internal = 8;
    bool explicit_non_internal = 9 [(internal) = false];
}
