/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.test.protobuf;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.test.protobuf";
option java_outer_classname = "FieldPathsTestProto";
option java_multiple_files = true;

import "google/protobuf/any.proto";

message StringHolder {
    string val = 1;
}

message StringHolderHolder {
    StringHolder holder = 1;
}

message AnyHolder {
    google.protobuf.Any val = 1;
}

message GenericHolder {
    StringHolder str = 1;
    StringHolderHolder holder_holder = 2;
    AnyHolder any = 3;
    GenericHolder generic = 4;
    enum Count {
        ZERO = 0;
        ONE = 1;
        TWO = 2;
        THREE = 3;
    }
    Count count = 5;
    int32 size = 6;
}
